version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
